config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  namespace :dashboard do
  get 'frontend_streams/index'
  end

  namespace :dashboard do
  get 'reports/index'
  end

  resources :datasift_subscriptions

  namespace :dashboard do

  end

  namespace :dashboard do
  get 'datsift/billing'
  end

  namespace :dashboard do
  get 'datsift/logs'
  end

  namespace :api , :defaults => {:format => :json} do
    namespace :v1 do
      get "leads" => 'leads#index'
      get 'reports/all'
      post 'lead_streams' => 'lead_stream#create_many'
    end
  end

  namespace :dashboard do
  get 'home/index'
  end

  namespace :dashboard do
  get 'import_manually_checked_leads/import'
  end

  namespace :dashboard do
  get 'classifications/bayesian_processor'
  end

  namespace :dashboard do
  get 'import_training_data/import_data'
  end

  namespace :dashboard do
    root 'leads#index'
    get 'leads/index'
    post 'leads/move_tweet_to_nonleads'
    get 'unchecked_leads/export_as_csv'
    get 'generate_datasift_query' => 'generate_query#datasift'
    resources :twitter_searches
    get 'word_counter' => 'word_counter#index'
    get 'word_counter/:word' => 'word_counter#show'
    get 'datsift/subscriptions'
    get 'datsift/subscriptions/:unique_stream_id' => 'datsift#subscriptions'
    get 'datsift/recreate_all'
  end

  mount Sidekiq::Web => '/sidekiq'

  post 'users' => 'users#create'


end

app/models/dashboard.rb
module Dashboard
  def self.table_name_prefix
    'dashboard_'
  end
end

app/models/dashboard/twitter_search.rb
# == Schema Information
#
# Table name: dashboard_twitter_searches
#
#  id          :integer          not null, primary key
#  created_at  :datetime
#  updated_at  :datetime
#  keyword     :string(255)
#  city        :string(255)
#  category_id :integer
#  city_id     :integer
#

class Dashboard::TwitterSearch < ActiveRecord::Base
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception

  layout "dashboard/application"

  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

end

app/controllers/dashboard/classifications_controller.rb
require 'location_checker'
require 'keyword_checker'
require 'url_checker'
require 'bayesian_classifier'

class Dashboard::ClassificationsController < ApplicationController
  def bayesian_processor
    bayesian_classifier = BayesianClassifier.new
    bayesian_classifier.process_all_unprocessed_leads
  end
end

app/controllers/dashboard/datsift_controller.rb
require 'datasift_functions'
require 'datasift_query'

class Dashboard::DatsiftController < Dashboard::ApplicationController
  def subscriptions
    datasift_call = DatasiftCalls.new
    subscriptions = datasift_call.get_push_subscriptions
    @all_subscriptions = subscriptions[:data][:subscriptions]

    @datasift_subscription = DatasiftSubscription.new



    @subscriptions = DatasiftSubscription.all
  end

  def billing
  end

  def logs
    datasift =  DatasiftCalls.new
    @logs = datasift.get_logs
  end

  def recreate_all
    datasift_functions = DatasiftFunctions.new

    datasift_functions.delay.recreate_all_subscriptions

    flash[:notice] = "Successfully added the recreate to the queue."
    redirect_to dashboard_datsift_subscriptions_path
  end

end

app/controllers/dashboard/frontend_streams_controller.rb
class Dashboard::FrontendStreamsController < Dashboard::ApplicationController
  def index
    @unique_lead_streams = UniqueLeadStream.all
  end
end

app/controllers/dashboard/generate_query_controller.rb
require 'datasift_query'

class Dashboard::GenerateQueryController < Dashboard::ApplicationController
  def datasift

    # Sample call to generate a datasift query
    # http://localhost:3000/dashboard/generate_datasift_query?keywords=beer,shots,party,cocktails&city=Chicago

    @keywords = params[:keywords]
    @city = params[:city]

    datasift_query = DatasiftQuery.new
    @query = datasift_query.generate(@keywords, @city)

  end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < Dashboard::ApplicationController
  def index

    twitter_search = TwitterSearch.new
    twitter_search.find_tweets(1)

    # users = User.all
    #
    # users.each do |user|
    #   twitter_search = TwitterSearch.new
    #   twitter_search.find_tweets(user.id)
    # end
  end
end

app/controllers/dashboard/import_manually_checked_leads_controller.rb
require 'import_manually_checked_leads'
require 'csv'

class Dashboard::ImportManuallyCheckedLeadsController < ApplicationController
  def import

    import_manually_checked_leads = ImportManuallyCheckedLeads.new
    import_manually_checked_leads.import_csv

  end
end

app/controllers/dashboard/import_training_data_controller.rb
require 'training_data'

class Dashboard::ImportTrainingDataController < ApplicationController
  def import_data
    training_data = TrainingData.new
    training_data.import_from_s3
  end
end

app/controllers/dashboard/leads_controller.rb
class Dashboard::LeadsController < Dashboard::ApplicationController
  def index
    #@leads = Lead.all
    @leads = Lead.paginate(:page => params[:page], :per_page => 10)
  end

  def move_tweet_to_nonleads

    lead_to_move = Lead.find(params[:lead_id])
    TrainingNonLead.create(tweet_body: lead_to_move.tweet_body)
    lead_to_move.destroy

    respond_to do |format|
      format.json { render :json => {:message => "Success"} }
    end
  end
end

app/controllers/dashboard/reports_controller.rb
class Dashboard::ReportsController < Dashboard::ApplicationController
  def index
  end
end

app/controllers/dashboard/twitter_searches_controller.rb
require 'twitter_search'

class Dashboard::TwitterSearchesController < Dashboard::ApplicationController
  before_action :set_dashboard_twitter_search, only: [:show, :edit, :update, :destroy]

  # GET /dashboard/twitter_searches
  # GET /dashboard/twitter_searches.json
  def index
    @dashboard_twitter_search = Dashboard::TwitterSearch.new
  end

  # GET /dashboard/twitter_searches/1
  # GET /dashboard/twitter_searches/1.json
  def show
  end

  # GET /dashboard/twitter_searches/new
  def new
    @dashboard_twitter_search = Dashboard::TwitterSearch.new
  end

  # GET /dashboard/twitter_searches/1/edit
  def edit
  end

  # POST /dashboard/twitter_searches
  # POST /dashboard/twitter_searches.json
  def create

    puts "WooHoo! it is where it should be"

    @dashboard_twitter_search = Dashboard::TwitterSearch.new(dashboard_twitter_search_params)

    city = City.find(params[:dashboard_twitter_search][:city_id])

    logger.debug "The terms used are: #{params[:dashboard_twitter_search][:keyword]}, #{city.city_name}, #{params[:dashboard_twitter_search][:category_id]}, #{params[:dashboard_twitter_search][:city_id]}"

    twitter_search = TwitterSearch.new
    twitter_search.delay.admin_find_tweet_using_keyword_and_city(params[:dashboard_twitter_search][:keyword], city.city_name, params[:dashboard_twitter_search][:category_id], params[:dashboard_twitter_search][:city_id])


    respond_to do |format|
      if @dashboard_twitter_search.save
        format.html { redirect_to @dashboard_twitter_search, notice: 'Twitter search was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard_twitter_search }
      else
        format.html { render :new }
        format.json { render json: @dashboard_twitter_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboard/twitter_searches/1
  # PATCH/PUT /dashboard/twitter_searches/1.json
  def update
    respond_to do |format|
      if @dashboard_twitter_search.update(dashboard_twitter_search_params)
        format.html { redirect_to @dashboard_twitter_search, notice: 'Twitter search was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard_twitter_search }
      else
        format.html { render :edit }
        format.json { render json: @dashboard_twitter_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/twitter_searches/1
  # DELETE /dashboard/twitter_searches/1.json
  def destroy
    @dashboard_twitter_search.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_twitter_searches_url, notice: 'Twitter search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_twitter_search
      @dashboard_twitter_search = Dashboard::TwitterSearch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_twitter_search_params
      params.require(:dashboard_twitter_search).permit(:keyword, :category_id, :city_id)
    end
end

app/controllers/dashboard/unchecked_leads_controller.rb
class Dashboard::UncheckedLeadsController < Dashboard::ApplicationController
  def export_as_csv

    @unchecked_leads = UncheckedLead.order(:id)

    respond_to do |format|
      format.html
      format.csv {render text: @unchecked_leads.to_csv}
    end

  end
end

app/controllers/dashboard/word_counter_controller.rb
require 'keyword_checker'

class Dashboard::WordCounterController < Dashboard::ApplicationController
  def index
    #@word_to_check = params[:word]
    @search_words = WordCounter.uniq.pluck(:word)
  end

  def show
    @word = params[:word]
    @tweets = WordCounter.where(word: @word.downcase)
  end

end

app/helpers/dashboard/classifications_helper.rb
module Dashboard::ClassificationsHelper
end

app/helpers/dashboard/datsift_helper.rb
module Dashboard::DatsiftHelper
end

app/helpers/dashboard/frontend_streams_helper.rb
module Dashboard::FrontendStreamsHelper
end

app/helpers/dashboard/generate_query_helper.rb
module Dashboard::GenerateQueryHelper
end

app/helpers/dashboard/home_helper.rb
module Dashboard::HomeHelper
end

app/views/dashboard/datsift/billing.html.erb
<h1>Dashboard::Datsift#billing</h1>
<p>Find me in app/views/dashboard/datsift/billing.html.erb</p>

app/views/dashboard/datsift/logs.html.erb
<div class="page-title">	<i class="icon-custom-left"></i>

  <h3>Subscription - <span class="semi-bold">Logs</span></h3>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="grid simple ">
      <div class="grid-title no-border">

      </div>
      <div class="grid-body no-border">
        <h3><span class="semi-bold">Logs</span></h3>
        <table class="table no-more-tables">
          <thead>
          <tr>
            <th style="width:14%">Subscription Id</th>
            <th style="width:27%">Message</th>
            <th style="width:6%">Request time</th>
          </tr>
          </thead>
          <tbody>

          <% @logs[:data][:log_entries].each do |log_item| %>
            <tr>
              <td class="v-align-middle"><%= log_item[:subscription_id] %></td>
              <td class="v-align-middle"><span class="muted"><%= log_item[:message] %></span>
              </td>
              <td><span class="muted"><%= log_item[:request_time] %></span>
              </td>
            </tr>
          <% end %>

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/datsift/subscriptions.html.erb
<div class="page-title">	<i class="icon-custom-left"></i>

  <h3><span class="semi-bold">Subscriptions</span></h3>
</div>


<div class="row">
  <div class="col-md-12">
    <div class="grid simple">
      <div class="grid-title no-border">
        <h3>New <span class="semi-bold">Subscription</span></h3>
      </div>
      <div class="grid-body no-border">
        <%= render "datasift_subscriptions/form" %>
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-md-12">
    <div class="grid simple ">
      <div class="grid-title no-border">

      </div>
      <div class="grid-body no-border">

        <h3><span class="semi-bold">All subscriptions through our dashboard</span> <span class="pull-right"><a href="<%= dashboard_datsift_recreate_all_path %>" class="btn btn-primary btn-cons">Recreate All</a></span></h3>



        <table class="table no-more-tables">
          <thead>
          <tr>
            <th style="width:10%">Subscription Id</th>
            <th style="width:10%">Hash Id</th>
            <th style="width:17%">Name</th>
            <th style="width:10%">Actions</th>
          </tr>
          </thead>
          <tbody>

          <% @subscriptions.each do |datasift_subscription|  %>

            <tr>
              <td class="v-align-middle"><%= datasift_subscription[:datasift_subscription_id] %></td>
              <td class="v-align-middle"><span class="muted"><%= datasift_subscription[:stream_hash] %></span>
              </td>
              <td><span class="muted"><%= datasift_subscription[:subscription_name] %></span>
              </td>
              <td>
                <%= link_to 'Destroy', datasift_subscription, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-cons" %>
              </td>
            </tr>

          <% end %>

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-md-12">
    <div class="grid simple ">
      <div class="grid-title no-border">

      </div>
      <div class="grid-body no-border">

        <h3><span class="semi-bold">All subscriptions on datasift</span></h3>



        <table class="table no-more-tables">
          <thead>
          <tr>
            <th style="width:10%">Subscription Id</th>
            <th style="width:10%">Hash Id</th>
            <th style="width:17%">Name</th>
            <th style="width:10%">Actions</th>
          </tr>
          </thead>
          <tbody>

          <% @all_subscriptions.each do |datasift_subscription|  %>

            <tr>
              <td class="v-align-middle"><%= datasift_subscription[:id] %></td>
              <td class="v-align-middle"><span class="muted"><%= datasift_subscription[:hash] %></span>
              </td>
              <td><span class="muted"><%= datasift_subscription[:name] %></span>
              </td>
              <td></td>
            </tr>

          <% end %>

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>