config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  namespace :dashboard do
  get 'frontend_streams/index'
  end

  namespace :dashboard do
  get 'reports/index'
  end

  resources :datasift_subscriptions

  namespace :dashboard do

  end

  namespace :dashboard do
  get 'datsift/billing'
  end

  namespace :dashboard do
  get 'datsift/logs'
  end

  namespace :api , :defaults => {:format => :json} do
    namespace :v1 do
      get "leads" => 'leads#index'
      get 'reports/all'
      post 'lead_streams' => 'lead_stream#create_many'
    end
  end

  namespace :dashboard do
  get 'home/index'
  end

  namespace :dashboard do
  get 'import_manually_checked_leads/import'
  end

  namespace :dashboard do
  get 'classifications/bayesian_processor'
  end

  namespace :dashboard do
  get 'import_training_data/import_data'
  end

  namespace :dashboard do
    root 'leads#index'
    get 'leads/index'
    post 'leads/move_tweet_to_nonleads'
    get 'unchecked_leads/export_as_csv'
    get 'generate_datasift_query' => 'generate_query#datasift'
    resources :twitter_searches
    get 'word_counter' => 'word_counter#index'
    get 'word_counter/:word' => 'word_counter#show'
    get 'datsift/subscriptions'
    get 'datsift/subscriptions/:unique_stream_id' => 'datsift#subscriptions'
    get 'datsift/recreate_all'
  end

  mount Sidekiq::Web => '/sidekiq'

  post 'users' => 'users#create'


end

app/models/dashboard.rb
module Dashboard
  def self.table_name_prefix
    'dashboard_'
  end
end

app/models/dashboard/twitter_search.rb
# == Schema Information
#
# Table name: dashboard_twitter_searches
#
#  id          :integer          not null, primary key
#  created_at  :datetime
#  updated_at  :datetime
#  keyword     :string(255)
#  city        :string(255)
#  category_id :integer
#  city_id     :integer
#

class Dashboard::TwitterSearch < ActiveRecord::Base
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception

  layout "dashboard/application"

  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

end

app/controllers/dashboard/classifications_controller.rb
require 'location_checker'
require 'keyword_checker'
require 'url_checker'
require 'bayesian_classifier'

class Dashboard::ClassificationsController < ApplicationController
  def bayesian_processor
    bayesian_classifier = BayesianClassifier.new
    bayesian_classifier.process_all_unprocessed_leads
  end
end

app/controllers/dashboard/datsift_controller.rb
require 'datasift_functions'
require 'datasift_query'

class Dashboard::DatsiftController < Dashboard::ApplicationController
  def subscriptions
    datasift_call = DatasiftCalls.new
    subscriptions = datasift_call.get_push_subscriptions
    @all_subscriptions = subscriptions[:data][:subscriptions]

    @datasift_subscription = DatasiftSubscription.new



    @subscriptions = DatasiftSubscription.all
  end

  def billing
  end

  def logs
    datasift =  DatasiftCalls.new
    @logs = datasift.get_logs
  end

  def recreate_all
    datasift_functions = DatasiftFunctions.new

    datasift_functions.delay.recreate_all_subscriptions

    flash[:notice] = "Successfully added the recreate to the queue."
    redirect_to dashboard_datsift_subscriptions_path
  end

end

app/controllers/dashboard/frontend_streams_controller.rb
class Dashboard::FrontendStreamsController < Dashboard::ApplicationController
  def index
    @unique_lead_streams = UniqueLeadStream.all
  end
end

app/controllers/dashboard/generate_query_controller.rb
require 'datasift_query'

class Dashboard::GenerateQueryController < Dashboard::ApplicationController
  def datasift

    # Sample call to generate a datasift query
    # http://localhost:3000/dashboard/generate_datasift_query?keywords=beer,shots,party,cocktails&city=Chicago

    @keywords = params[:keywords]
    @city = params[:city]

    datasift_query = DatasiftQuery.new
    @query = datasift_query.generate(@keywords, @city)

  end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < Dashboard::ApplicationController
  def index

    twitter_search = TwitterSearch.new
    twitter_search.find_tweets(1)

    # users = User.all
    #
    # users.each do |user|
    #   twitter_search = TwitterSearch.new
    #   twitter_search.find_tweets(user.id)
    # end
  end
end

app/controllers/dashboard/import_manually_checked_leads_controller.rb
require 'import_manually_checked_leads'
require 'csv'

class Dashboard::ImportManuallyCheckedLeadsController < ApplicationController
  def import

    import_manually_checked_leads = ImportManuallyCheckedLeads.new
    import_manually_checked_leads.import_csv

  end
end

app/controllers/dashboard/import_training_data_controller.rb
require 'training_data'

class Dashboard::ImportTrainingDataController < ApplicationController
  def import_data
    training_data = TrainingData.new
    training_data.import_from_s3
  end
end

app/controllers/dashboard/leads_controller.rb
class Dashboard::LeadsController < Dashboard::ApplicationController
  def index
    #@leads = Lead.all
    @leads = Lead.paginate(:page => params[:page], :per_page => 10)
  end

  def move_tweet_to_nonleads

    lead_to_move = Lead.find(params[:lead_id])
    TrainingNonLead.create(tweet_body: lead_to_move.tweet_body)
    lead_to_move.destroy

    respond_to do |format|
      format.json { render :json => {:message => "Success"} }
    end
  end
end

app/controllers/dashboard/reports_controller.rb
class Dashboard::ReportsController < Dashboard::ApplicationController
  def index
  end
end

app/controllers/dashboard/twitter_searches_controller.rb
require 'twitter_search'

class Dashboard::TwitterSearchesController < Dashboard::ApplicationController
  before_action :set_dashboard_twitter_search, only: [:show, :edit, :update, :destroy]

  # GET /dashboard/twitter_searches
  # GET /dashboard/twitter_searches.json
  def index
    @dashboard_twitter_search = Dashboard::TwitterSearch.new
  end

  # GET /dashboard/twitter_searches/1
  # GET /dashboard/twitter_searches/1.json
  def show
  end

  # GET /dashboard/twitter_searches/new
  def new
    @dashboard_twitter_search = Dashboard::TwitterSearch.new
  end

  # GET /dashboard/twitter_searches/1/edit
  def edit
  end

  # POST /dashboard/twitter_searches
  # POST /dashboard/twitter_searches.json
  def create

    puts "WooHoo! it is where it should be"

    @dashboard_twitter_search = Dashboard::TwitterSearch.new(dashboard_twitter_search_params)

    city = City.find(params[:dashboard_twitter_search][:city_id])

    logger.debug "The terms used are: #{params[:dashboard_twitter_search][:keyword]}, #{city.city_name}, #{params[:dashboard_twitter_search][:category_id]}, #{params[:dashboard_twitter_search][:city_id]}"

    twitter_search = TwitterSearch.new
    twitter_search.delay.admin_find_tweet_using_keyword_and_city(params[:dashboard_twitter_search][:keyword], city.city_name, params[:dashboard_twitter_search][:category_id], params[:dashboard_twitter_search][:city_id])


    respond_to do |format|
      if @dashboard_twitter_search.save
        format.html { redirect_to @dashboard_twitter_search, notice: 'Twitter search was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard_twitter_search }
      else
        format.html { render :new }
        format.json { render json: @dashboard_twitter_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboard/twitter_searches/1
  # PATCH/PUT /dashboard/twitter_searches/1.json
  def update
    respond_to do |format|
      if @dashboard_twitter_search.update(dashboard_twitter_search_params)
        format.html { redirect_to @dashboard_twitter_search, notice: 'Twitter search was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard_twitter_search }
      else
        format.html { render :edit }
        format.json { render json: @dashboard_twitter_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/twitter_searches/1
  # DELETE /dashboard/twitter_searches/1.json
  def destroy
    @dashboard_twitter_search.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_twitter_searches_url, notice: 'Twitter search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_twitter_search
      @dashboard_twitter_search = Dashboard::TwitterSearch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_twitter_search_params
      params.require(:dashboard_twitter_search).permit(:keyword, :category_id, :city_id)
    end
end

app/controllers/dashboard/unchecked_leads_controller.rb
class Dashboard::UncheckedLeadsController < Dashboard::ApplicationController
  def export_as_csv

    @unchecked_leads = UncheckedLead.order(:id)

    respond_to do |format|
      format.html
      format.csv {render text: @unchecked_leads.to_csv}
    end

  end
end

app/controllers/dashboard/word_counter_controller.rb
require 'keyword_checker'

class Dashboard::WordCounterController < Dashboard::ApplicationController
  def index
    #@word_to_check = params[:word]
    @search_words = WordCounter.uniq.pluck(:word)
  end

  def show
    @word = params[:word]
    @tweets = WordCounter.where(word: @word.downcase)
  end

end

app/helpers/dashboard/classifications_helper.rb
module Dashboard::ClassificationsHelper
end

app/helpers/dashboard/datsift_helper.rb
module Dashboard::DatsiftHelper
end

app/helpers/dashboard/frontend_streams_helper.rb
module Dashboard::FrontendStreamsHelper
end

app/helpers/dashboard/generate_query_helper.rb
module Dashboard::GenerateQueryHelper
end

app/helpers/dashboard/home_helper.rb
module Dashboard::HomeHelper
end

app/views/layouts/dashboard/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <meta charset="utf-8" />
  <title>Webarch - Responsive Admin Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta content="" name="description" />
  <meta content="" name="author" />

  <%= stylesheet_link_tag    'dashboard/application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- BEGIN CSS TEMPLATE -->
  <link href="assets/css/custom-icon-set.css" rel="stylesheet" type="text/css"/>
  <!-- END CSS TEMPLATE -->

  <%= csrf_meta_tags %>

</head>
<!-- END HEAD -->

<!-- BEGIN BODY -->
<body class="">
<!-- BEGIN HEADER -->
<div class="header navbar navbar-inverse ">
  <!-- BEGIN TOP NAVIGATION BAR -->
  <div class="navbar-inner">
    <div class="header-seperation">
      <ul class="nav pull-left notifcation-center" id="main-menu-toggle-wrapper" style="display:none">
        <li class="dropdown"> <a id="main-menu-toggle" href="#main-menu"  class="" > <div class="iconset top-menu-toggle-white"></div> </a> </li>
      </ul>
      <!-- BEGIN LOGO -->
      <a href="index.html"><img src="assets/img/logo.png" class="logo" alt=""  data-src="assets/img/logo.png" data-src-retina="assets/img/logo2x.png" width="106" height="21"/></a>
      <!-- END LOGO -->
      <ul class="nav pull-right notifcation-center">
        <li class="dropdown" id="header_task_bar"> <a href="index.html" class="dropdown-toggle active" data-toggle=""> <div class="iconset top-home"></div> </a> </li>
        <li class="dropdown" id="header_inbox_bar" > <a href="email.html" class="dropdown-toggle" > <div class="iconset top-messages"></div>  <span class="badge" id="msgs-badge">2</span> </a></li>
        <li class="dropdown" id="portrait-chat-toggler" style="display:none"> <a href="#sidr" class="chat-menu-toggle"> <div class="iconset top-chat-white "></div> </a> </li>
      </ul>
    </div>
    <!-- END RESPONSIVE MENU TOGGLER -->
    <div class="header-quick-nav" >
      <!-- BEGIN TOP NAVIGATION MENU -->
      <div class="pull-left">
        <ul class="nav quick-section">
          <li class="quicklinks"> <a href="#" class="" id="layout-condensed-toggle" >
            <div class="iconset top-menu-toggle-dark"></div>
          </a> </li>
        </ul>
        <ul class="nav quick-section">
          <li class="quicklinks"> <a href="#" class="" >
            <div class="iconset top-reload"></div>
          </a> </li>
          <li class="quicklinks"> <span class="h-seperate"></span></li>
          <li class="quicklinks"> <a href="#" class="" >
            <div class="iconset top-tiles"></div>
          </a> </li>
          <li class="m-r-10 input-prepend inside search-form no-boarder">
            <span class="add-on"> <span class="iconset top-search"></span></span>
            <input name="" type="text"  class="no-boarder " placeholder="Search Dashboard" style="width:250px;">
          </li>
        </ul>
      </div>
      <!-- END TOP NAVIGATION MENU -->
      <!-- BEGIN CHAT TOGGLER -->
      <div class="pull-right">
        <div class="chat-toggler">
          <a href="#" class="dropdown-toggle" id="my-task-list" data-placement="bottom"  data-content='' data-toggle="dropdown" data-original-title="Notifications">
            <div class="user-details">
              <div class="username">
                <span class="badge badge-important">3</span>
                John <span class="bold">Smith</span>
              </div>
            </div>
            <div class="iconset top-down-arrow"></div>
          </a>
          <div id="notification-list" style="display:none">
            <div style="width:300px">
              <div class="notification-messages info">
                <div class="user-profile">
                  <img src="assets/img/profiles/d.jpg"  alt="" data-src="assets/img/profiles/d.jpg" data-src-retina="assets/img/profiles/d2x.jpg" width="35" height="35">
                </div>
                <div class="message-wrapper">
                  <div class="heading">
                    David Nester - Commented on your wall
                  </div>
                  <div class="description">
                    Meeting postponed to tomorrow
                  </div>
                  <div class="date pull-left">
                    A min ago
                  </div>
                </div>
                <div class="clearfix"></div>
              </div>
              <div class="notification-messages danger">
                <div class="iconholder">
                  <i class="icon-warning-sign"></i>
                </div>
                <div class="message-wrapper">
                  <div class="heading">
                    Server load limited
                  </div>
                  <div class="description">
                    Database server has reached its daily capicity
                  </div>
                  <div class="date pull-left">
                    2 mins ago
                  </div>
                </div>
                <div class="clearfix"></div>
              </div>
              <div class="notification-messages success">
                <div class="user-profile">
                  <img src="assets/img/profiles/h.jpg"  alt="" data-src="assets/img/profiles/h.jpg" data-src-retina="assets/img/profiles/h2x.jpg" width="35" height="35">
                </div>
                <div class="message-wrapper">
                  <div class="heading">
                    You haveve got 150 messages
                  </div>
                  <div class="description">
                    150 newly unread messages in your inbox
                  </div>
                  <div class="date pull-left">
                    An hour ago
                  </div>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
          </div>
          <div class="profile-pic">
            <img src="assets/img/profiles/avatar_small.jpg"  alt="" data-src="assets/img/profiles/avatar_small.jpg" data-src-retina="assets/img/profiles/avatar_small2x.jpg" width="35" height="35" />
          </div>
        </div>
        <ul class="nav quick-section ">
          <li class="quicklinks">
            <a data-toggle="dropdown" class="dropdown-toggle  pull-right " href="#" id="user-options">
              <div class="iconset top-settings-dark "></div>
            </a>
            <ul class="dropdown-menu  pull-right" role="menu" aria-labelledby="user-options">
              <li><a href="user-profile.html"> My Account</a>
              </li>
              <li><a href="calender.html">My Calendar</a>
              </li>
              <li><a href="email.html"> My Inbox&nbsp;&nbsp;<span class="badge badge-important animated bounceIn">2</span></a>
              </li>
              <li class="divider"></li>
              <li><a href="login.html"><i class="fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>
            </ul>
          </li>
          <li class="quicklinks"> <span class="h-seperate"></span></li>
          <li class="quicklinks">
            <a id="chat-menu-toggle" href="#sidr" class="chat-menu-toggle" ><div class="iconset top-chat-dark "><span class="badge badge-important hide" id="chat-message-count">1</span></div>
            </a>
            <div class="simple-chat-popup chat-menu-toggle hide" >
              <div class="simple-chat-popup-arrow"></div><div class="simple-chat-popup-inner">
              <div style="width:100px">
                <div class="semi-bold">David Nester</div>
                <div class="message">Hey you there </div>
              </div>
            </div>
            </div>
          </li>
        </ul>
      </div>
      <!-- END CHAT TOGGLER -->
    </div>
    <!-- END TOP NAVIGATION MENU -->

  </div>
  <!-- END TOP NAVIGATION BAR -->
</div>

<!-- END HEADER -->
<!-- BEGIN CONTAINER -->
<div class="page-container row">
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar" id="main-menu">
  <!-- BEGIN MINI-PROFILE -->
  <div class="page-sidebar-wrapper" id="main-menu-wrapper">

    <!-- END MINI-PROFILE -->
    <!-- BEGIN SIDEBAR MENU -->
    <ul style="margin-top: 20px;">
      <li class="start"> <a href="<%= dashboard_root_path %>"> <i class="fa fa-area-chart"></i> <span class="title">Dashboard</span> <span class="selected"></span>  </a>
      </li>
      <li class=""> <a href="<%= dashboard_datsift_subscriptions_path %>"> <i class="fa fa-th"></i> <span class="title">Datasift Subscriptions</span></a> </li>
      <li class=""> <a href="<%= dashboard_generate_datasift_query_path %>"> <i class="fa fa fa-adjust"></i> <span class="title">Query Generator</span> </a>
      </li>
      <li class=""> <a href="<%= dashboard_twitter_searches_path %>"> <i class="fa fa-search"></i> <span class="title">Twitter Search</span> </a>
      </li>
      <li class=""> <a href="<%= dashboard_word_counter_path %>"> <i class="fa fa-search"></i> <span class="title">Word Counter</span> </a>
      </li>
      <li class=""> <a href="<%= dashboard_frontend_streams_index_path %>"> <i class="fa fa-bars"></i> <span class="title">Frontend Streams</span> </a>
      </li>
    </ul>

    <div class="clearfix"></div>
    <!-- END SIDEBAR MENU -->
  </div>
</div>
<a href="#" class="scrollup">Scroll</a>
<div class="footer-widget">
  <div class="progress transparent progress-small no-radius no-margin">
    <div class="progress-bar progress-bar-success animate-progress-bar" data-percentage="79%" style="width: 79%;"></div>
  </div>
  <div class="pull-right">
    <div class="details-status">
      <span class="animate-number" data-value="86" data-animation-duration="560">86</span>%
    </div>
    <a href="lockscreen.html"><i class="fa fa-power-off"></i></a></div>
</div>
<!-- END SIDEBAR -->
<!-- BEGIN PAGE CONTAINER-->
<div class="page-content">
<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
<div id="portlet-config" class="modal hide">
  <div class="modal-header">
    <button data-dismiss="modal" class="close" type="button"></button>
    <h3>Widget Settings</h3>

  </div>
  <div class="modal-body">Widget settings form goes here</div>
</div>
<div class="clearfix"></div>
<div class="content">

<%= yield %>

</div>
<!-- END PAGE -->
</div>
</div>

<!-- END CONTAINER -->

<!-- BEGIN CORE JS FRAMEWORK-->



<!-- BEGIN PAGE LEVEL JS -->

<%= javascript_include_tag 'dashboard/application', 'data-turbolinks-track' => true %>

<!--<script src="assets/plugins/jquery-sparkline/jquery-sparkline.js"></script>-->
<!--<script src="assets/plugins/jquery-numberAnimate/jquery.animateNumbers.js" type="text/javascript"></script>-->
<!--<script src="assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>-->
<!-- END PAGE LEVEL PLUGINS -->
<script>
  //Too Small for new file - Helps the to tick all options in the table
  $('table .checkbox input').click( function() {
    if($(this).is(':checked')){
      $(this).parent().parent().parent().toggleClass('row_selected');
    }
    else{
      $(this).parent().parent().parent().toggleClass('row_selected');
    }
  });
  // Demo charts - not required
  $('.customer-sparkline').each(function () {
    $(this).sparkline('html', { type:$(this).attr("data-sparkline-type"), barColor:$(this).attr("data-sparkline-color") , enableTagOptions: true });
  });
</script>

</body>

</html>