config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  namespace :dashboard do
  get 'frontend_streams/index'
  end

  namespace :dashboard do
  get 'reports/index'
  end

  resources :datasift_subscriptions

  namespace :dashboard do

  end

  namespace :dashboard do
  get 'datsift/billing'
  end

  namespace :dashboard do
  get 'datsift/logs'
  end

  namespace :api , :defaults => {:format => :json} do
    namespace :v1 do
      get "leads" => 'leads#index'
      get 'reports/all'
      post 'lead_streams' => 'lead_stream#create_many'
    end
  end

  namespace :dashboard do
  get 'home/index'
  end

  namespace :dashboard do
  get 'import_manually_checked_leads/import'
  end

  namespace :dashboard do
  get 'classifications/bayesian_processor'
  end

  namespace :dashboard do
  get 'import_training_data/import_data'
  end

  namespace :dashboard do
    root 'leads#index'
    get 'leads/index'
    post 'leads/move_tweet_to_nonleads'
    get 'unchecked_leads/export_as_csv'
    get 'generate_datasift_query' => 'generate_query#datasift'
    resources :twitter_searches
    get 'word_counter' => 'word_counter#index'
    get 'word_counter/:word' => 'word_counter#show'
    get 'datsift/subscriptions'
    get 'datsift/subscriptions/:unique_stream_id' => 'datsift#subscriptions'
    get 'datsift/recreate_all'
  end

  mount Sidekiq::Web => '/sidekiq'

  post 'users' => 'users#create'


end

app/models/datasift_subscription.rb
# == Schema Information
#
# Table name: datasift_subscriptions
#
#  id                       :integer          not null, primary key
#  datasift_subscription_id :string(255)
#  stream_hash              :string(255)
#  subscription_name        :string(255)
#  query                    :text
#  created_at               :datetime
#  updated_at               :datetime
#  category_id              :integer
#  city_id                  :integer
#

class DatasiftSubscription < ActiveRecord::Base
  validates_presence_of :stream_hash, :subscription_name, :category_id, :city_id
end

app/controllers/datasift_subscriptions_controller.rb
require 'datasift_calls'

class DatasiftSubscriptionsController < ApplicationController
  before_action :set_datasift_subscription, only: [:show, :edit, :update, :destroy]

  # GET /datasift_subscriptions
  # GET /datasift_subscriptions.json
  def index
    @datasift_subscriptions = DatasiftSubscription.all
  end

  # GET /datasift_subscriptions/1
  # GET /datasift_subscriptions/1.json
  def show
  end

  # GET /datasift_subscriptions/new
  def new
    @datasift_subscription = DatasiftSubscription.new
  end

  # GET /datasift_subscriptions/1/edit
  def edit
  end

  # POST /datasift_subscriptions
  # POST /datasift_subscriptions.json
  def create
    @datasift_subscription = DatasiftSubscription.new(datasift_subscription_params)

    datasift_calls = DatasiftCalls.new
    new_subscription = datasift_calls.create_push_subscription(params[:datasift_subscription][:stream_hash], params[:datasift_subscription][:subscription_name] )

    @datasift_subscription[:datasift_subscription_id] = new_subscription[:data][:id]


    respond_to do |format|
      if @datasift_subscription.save
        #format.html { redirect_to @datasift_subscription, notice: 'Datasift subscription was successfully created.' }
        flash[:notice] = "Datasift subscription was successfully created with id: #{@datasift_subscription.id}"
        format.html { redirect_to dashboard_datsift_subscriptions_path }
        format.json { render :show, status: :created, location: @datasift_subscription }
      else
        format.html { render :new }
        format.json { render json: @datasift_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datasift_subscriptions/1
  # PATCH/PUT /datasift_subscriptions/1.json
  def update
    respond_to do |format|
      if @datasift_subscription.update(datasift_subscription_params)
        format.html { redirect_to @datasift_subscription, notice: 'Datasift subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @datasift_subscription }
      else
        format.html { render :edit }
        format.json { render json: @datasift_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datasift_subscriptions/1
  # DELETE /datasift_subscriptions/1.json
  def destroy

    datasift_subscription_attributes = @datasift_subscription.attributes
    datasift_subscription_attributes.delete ["id"]
    deleted_datasift_subscription = DeletedDatasiftSubscription.new(datasift_subscription_attributes)

    if deleted_datasift_subscription.save
      @datasift_subscription.destroy
      respond_to do |format|

        datasift_calls = DatasiftCalls.new
        datasift_calls.delete_push_subscription(@datasift_subscription[:datasift_subscription_id])

        flash[:notice] = "Datasift subscription was successfully destroyed."
        format.html { redirect_to dashboard_datsift_subscriptions_path }
        format.json { head :no_content }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datasift_subscription
      @datasift_subscription = DatasiftSubscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datasift_subscription_params
      params.require(:datasift_subscription).permit(:datasift_subscription_id, :stream_hash, :subscription_name, :query, :city_id, :category_id)
    end
end

app/helpers/datasift_subscriptions_helper.rb
module DatasiftSubscriptionsHelper
end

app/views/datasift_subscriptions/_form.html.erb
<%= form_for(@datasift_subscription) do |f| %>

  <% if @datasift_subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datasift_subscription.errors.count, "error") %> prohibited this datasift_subscription from being saved:</h2>

      <ul>
        <% @datasift_subscription.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <% if !notice.nil? %>
    <div class="alert alert-success">
      <button data-dismiss="alert" class="close"></button>
      Success: <%= notice %>
    </div>
  <% end %>

  <!--<div class="field">-->
    <%# f.label :datasift_subscription_id %><br>
    <%# f.text_field :datasift_subscription_id %>
  <!--</div>-->

  <div id="create_subscription">
    <div class="row">
      <div class="col-md-6">
          <!--<input placeholder="Stream hash" class="form-control" type="text">-->
        <%= f.text_field :stream_hash, placeholder: "Stream hash", class: "form-control"  %>

      </div>
      <div class="col-md-6">
        <!--<input placeholder="Subscription name" class="form-control" type="text">-->
        <%= f.text_field :subscription_name, placeholder: "Subscription name", class: "form-control" %>
      </div>
      <!--<div class="col-md-2">-->
        <!--<button class="btn btn-primary btn-cons" type="button">Create Subscription</button>-->
      <!--</div>-->
    </div>

    <div class="row">
      <div class="col-md-6">
        <%= f.collection_select :category_id, Category.all, :id, :name, {:prompt => 'Select category'}, class: "form-control" %>
      </div>
      <div class="col-md-6">
        <%= f.collection_select :city_id, City.all, :id, :city_name, {:prompt => 'Select city'}, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <%= f.text_area :query, placeholder: "CSDL query used for this hash", class: "form-control", rows: 5 %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= f.submit :class => "btn btn-primary btn-cons" %>
      </div>
    </div>

  </div>


  <div class="field">

  </div>
  <div class="actions">

  </div>
<% end %>

app/views/datasift_subscriptions/edit.html.erb
<h1>Editing datasift_subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @datasift_subscription %> |
<%= link_to 'Back', datasift_subscriptions_path %>

app/views/datasift_subscriptions/index.html.erb
<h1>Listing datasift_subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Datasift subscription</th>
      <th>Stream hash</th>
      <th>Subscription name</th>
      <th>Query</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @datasift_subscriptions.each do |datasift_subscription| %>
      <tr>
        <td><%= datasift_subscription.datasift_subscription_id %></td>
        <td><%= datasift_subscription.stream_hash %></td>
        <td><%= datasift_subscription.subscription_name %></td>
        <td><%= datasift_subscription.query %></td>
        <td><%= link_to 'Show', datasift_subscription %></td>
        <td><%= link_to 'Edit', edit_datasift_subscription_path(datasift_subscription) %></td>
        <td><%= link_to 'Destroy', datasift_subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Datasift subscription', new_datasift_subscription_path %>

app/views/datasift_subscriptions/new.html.erb
<h1>New datasift_subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', datasift_subscriptions_path %>

app/views/datasift_subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datasift subscription:</strong>
  <%= @datasift_subscription.datasift_subscription_id %>
</p>

<p>
  <strong>Stream hash:</strong>
  <%= @datasift_subscription.stream_hash %>
</p>

<p>
  <strong>Subscription name:</strong>
  <%= @datasift_subscription.subscription_name %>
</p>

<p>
  <strong>Query:</strong>
  <%= @datasift_subscription.query %>
</p>

<%= link_to 'Edit', edit_datasift_subscription_path(@datasift_subscription) %> |
<%= link_to 'Back', datasift_subscriptions_path %>